### PR TITLE
Specify license for Xtensa port

### PR DESCRIPTION
**Pull request by afoxley**
Specify LICENSE for Xtensa port

Description
-----------
Each port subdirectory should specify the license of the source contained.

Test Steps
-----------
NA

Related Issue
-----------
NA

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by afoxley** [comment]
@ianstcdns Please review

**Review by ActoryOu — APPROVED** [review]

**Comment by ianstcdns** [comment]
Given that the MIT license requires the copyright message to be placed in every file (“substantial portions”) regardless, it does seem a bit redundant to include a separate file with the same message.  Is this something that Amazon is planning to standardize across the Partner-Supported and Community-Supported repos?  Because only 2 of the 9-10 ports have license files, although these appear to be named LICENSE.md instead.  

If this is part of a broader effort to standardize to this practice, I’m happy to go along with it, but if it’s only applied to the Xtensa port, I think our preference would be to leave this as-is.  

@aggarg @RichardBarry

**Comment by ianstcdns** [comment]
Thanks; sounds good.  I don't see an approve button, but I'm fine with this getting merged as-is.

**Comment by aggarg** [comment]
As @afoxley pointed, the top level LICENSE file expects each port to have a LICENSE file. At the moment, several ports do not have a LICENSE file and that needs to be fixed. Thank you for raising the PR @afoxley  and thank you for reviewing it @ianstcdns.

**Review by aggarg — APPROVED** [review]

**Pull request merged**
