### PR TITLE
Adding Infineon AURIX TC3xx portables for the Tasking compiler

### PR DESCRIPTION
**Pull request by schaazzz**
Adding Infineon AURIX TC3xx portables for the Tasking compiler

Description
-----------
Infineon's officially supported Kernel Port for the AURIX TC3xx MCUs based on the Tasking compiler

Test Steps
-----------
Required tests (register/context switch and interrupt nesting) were implemented and the corresponding ADS project is included in the parallel pull request for the **FreeRTOS-Partner-Supported-Demos** repository.

Related Issue
-----------
None

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by paulbartell** [comment]
Thanks very much for the contribution. Quite a few folks over the past few years have requested TriCore ports so i'm glad we have another port to point them towards.

Could you please add an SPDX License Identifier line to each file? Something like:

```
SPDX-License-Identifier: BSL-1.0
```

**Comment by amazonKamath** [comment]
@schaazzz did you get a chance to address the review comments by @paulbartell.

**Comment by schaazzz** [comment]
Still pending, will be done by next week

**Review by aggarg — APPROVED** [review]

**Review by amazonKamath — APPROVED** [review]

**Comment by dongsheng-autra** [comment]
@schaazzz  Hi schaazzz, is there SMP plan for tricore/AURIX

**Comment by maxdd** [comment]
Hello @schaazzz any update on your post above?

**Pull request merged**
